import { Dimensions, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    marginTop: 24,
    flex: 1,
    backgroundColor: '#F3F5FF',
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
  },
  scrollView: {
    marginVertical: 4,
    width: Dimensions.get('window').width,
    paddingHorizontal:14,
  },
  content:{
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    paddingHorizontal:24,
    marginVertical: 8,
  },
  header:{
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    paddingHorizontal:24,
    marginVertical: 4,
  },
  title:{
    fontWeight: 'bold',
    fontFamily: 'Poppins_700Bold',
    fontSize: 24,
    color: '#566DEA',
    marginVertical: 2
  },
  petData:{
    flexDirection: 'column',
  },
  petAge:{
    fontWeight: 'normal',
    fontFamily: 'Poppins_400Regular',
    fontSize: 16,
    color: '#566DEA',
    marginRight: 16,
  },
  headerTitle:{
    fontWeight: 'normal',
    fontFamily: 'Poppins_400Regular',
    fontSize: 24,
    color: '#566DEA',
  },
  petItem:{
    borderRadius: 8,
    backgroundColor:"#FFF",
    alignItems: 'flex-start',
    paddingVertical: 8,
    paddingHorizontal: 14,
    marginVertical: 8,
    marginHorizontal: 8,
    elevation:4,
  },
  itemRow:{
    flexDirection: 'row',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-between'
  },
  medicalRecordTitle:{
    fontWeight: 'normal',
    fontFamily: 'Poppins_400Regular',
    fontSize: 18,
    color: '#566DEA',
    marginVertical: 4,
  },
  medicalRecordDate:{
    fontWeight: 'normal',
    fontFamily: 'Poppins_400Regular',
    fontSize: 18,
    color: '#0000004d',
    marginVertical: 4,
  },
  repeatApplicationDate:{
    fontWeight: 'normal',
    fontFamily: 'Poppins_400Regular',
    fontSize: 18,
    color: '#000',
    marginVertical: 4,
  },
  line:{
    width: 30,
    height: 2,
    backgroundColor: '#566DEA',
  },
  buttonRounded:{
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "transparent",   
    alignItems:'center',
    justifyContent: 'center',
    marginVertical: 8,
  },
  addPetButton:{
    width: '100%',
    borderRadius: 8,
    backgroundColor:"transparent",
    flexDirection: 'row',      
    alignItems:'center',
    justifyContent: 'center',
    padding: 32,
    marginVertical: 4,
  },
  addPetButtonText:{
    fontWeight: 'normal',
    fontSize: 18,
    color: '#566DEA',
    fontFamily: 'Poppins_400Regular',
  },
  petImage:{ 
    width: 64,
    height: 64,
    borderRadius: 32,
    resizeMode: 'cover',
    marginRight: 8,
  },
});